Algoritmo "q7"
// A Loja Mamão com Açúcar está vendendo seus produtos em até 10 prestações sem juros.
//Faça um algoritmo que pergunte um valor de uma compra, o número de prestações
//escolhidas e apresente como resultado o valor das prestações.
Var
a: real
b: real

Inicio
escreva("Qual o valor da compra?")
leia(a)

escreva("Qual o número de prestações escolhidas?")
leia(b)

escreva("O resultado do valor das prestações é de: R$", a / b)

Fimalgoritmo