Algoritmo "q2"
//Desenvolver um programa que apresente o total da soma de N números inteiros do
//número 1 até N
Var
contador, acumulador, n: inteiro

Inicio
escreva("Insira um número: ")
leia(n)

acumulador <- 0

para contador de 0 ate n faca
     acumulador <- acumulador + contador
     contador <- contador + 1
fimpara
     escreva("Aqui está a soma dos números de 1 até", n, " é", acumulador)
Fimalgoritmo