Algoritmo "q3"
//Fazer um algoritmo que pergunte um valor e exiba como resposta este valor
//com acréscimo de 18% e também o mesmo valor inicial com desconto de 65%
Var
acres, desc: real
valor: inteiro
Inicio
escreva("Insira um valor:")
leia(valor)

acres <- valor * 0.18
desc <- valor * 0.65

escreva("O valor com acréscimo de 18% é igual a", acres, " e o valor com desconto de 65% é igual a", desc)

Fimalgoritmo