Algoritmo "q15"
//Desenvolver um programa que apresente a série de Fibonacci até o décimo quinto
//termo. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34, ...
//etc. Ela se caracteriza pela soma de um termo posterior com seu anterior subsequente
Var
a: real
b: real
c:real
Inicio
a <- 0
b <- 1

enquanto (a <= 610) faca
    c <- a + b
    escreval("O número da sequência Fibonacci é", c)
fimenquanto
Fimalgoritmo